root: ./

# Configuration for the book
structure:
  readme: README.md
  summary: SUMMARY.md

# Configuration for PDF generation
pdf:
  page_numbers: true
  font_size: 12
  paper_size: a4
  chapter_mark: pagebreak
  page_break_before: h1

# Plugin configuration
plugins:
  - search
  - sharing
  - fontsettings
  - theme-default

# Redirects for legacy URLs
redirects:
  /docs/python-sdk: /python-sdk
  /docs/api: /api-reference
  /docs/guides: /platform-guide

# Variables that can be used in documentation
variables:
  version: "1.0.0"
  api_base_url: "https://app.knowrithm.org/api/v1"
  sdk_version: "1.0.0"
  python_min_version: "3.8"
  support_email: "support@knowrithm.org"
  discord_url: "https://discord.gg/cHHWfghJrR"
  github_url: "https://github.com/Knowrithm/knowrithm-py"

# Link validation
links:
  validation: warning
  
# Table of contents settings
toc:
  before: |
    <div class="toc-header">
      <h3>Knowrithm Documentation</h3>
      <p>Version {{book.version}}</p>
    </div>
  after: |
    <div class="toc-footer">
      <p><a href="{{book.discord_url}}" target="_blank">Join our Discord</a></p>
      <p><a href="{{book.github_url}}" target="_blank">GitHub Repository</a></p>
    </div>

# Format settings
format:
  ebook:
    theme: white
  pdf:
    theme: white
    margin:
      top: 56
      bottom: 56
      left: 62
      right: 62

# Search configuration
search:
  maxIndexSize: 1000000
  fuzziness: 2
  distance: 100